[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy =  '''
    object-src 'none';
    img-src https:;
    default-src 'self' unpkg.com *.unpkg.com websitecarbon.com *.websitecarbon.com *.thegreenwebfoundation.org;
    style-src 'self' 'unsafe-inline';
    base-uri 'self';
    form-action 'self';
    frame-ancestors 'none';'''
    Access-Control-Allow-Origin = "*"