[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy =  '''
    object-src 'none';
    img-src https:;
    default-src 'self'
    style-src 'self' 'unsafe-inline'
    frame-ancestors 'none';'''
    Access-Control-Allow-Origin = "*"
    connect-src https://www.the-public-good.com/ https://www.thegreenwebfoundation.org
