[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy =  '''
    style-src 'self' 'unsafe-inline';
    default-src 'self' 'unsafe-inline';
    object-src 'none';
    img-src https:;
    script-src 'self' 'unsafe-inline';
    frame-ancestors 'none';'''

