[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy =  '''
    style-src 'self';
    default-src 'self';
    object-src 'none';
    img-src https:;
    script-src 'self' https://unpkg.com/website-carbon-badges@^1/b.min.js; # 'unsafe-inline'
    frame-ancestors 'none';'''

